// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Used by Prisma CLI commands (migrations, studio).
    // For Supabase use the DIRECT connection string (port 5432) here —
    // DDL through the transaction pooler (port 6543) can fail.
    url: env("DATABASE_URL"),
  },
});
